# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wakey < Formula
  desc "Keep your Mac awake by gently moving the cursor"
  homepage "https://github.com/Nitesh000/wakey"
  version "0.0.3"
  license "MIT"
  depends_on :macos

  on_intel do
    url "https://github.com/Nitesh000/wakey/releases/download/v0.0.3/wakey_0.0.3_darwin_amd64.tar.gz"
    sha256 "e4a17fb73f74a560cfad15c7259d19a7dea281490531299893eee64e8ae5579c"

    def install
      bin.install "wakey"
    end
  end
  on_arm do
    url "https://github.com/Nitesh000/wakey/releases/download/v0.0.3/wakey_0.0.3_darwin_arm64.tar.gz"
    sha256 "30572f7e408d0cfcaf1b6bb23bc6bec864399cb65e932a20de52f255b31992c5"

    def install
      bin.install "wakey"
    end
  end
end
