# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skmp < Formula
  desc "Skill marketplace for AI agent skills"
  homepage "https://github.com/Nitesh000/skmp"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Nitesh000/skmp/releases/download/v0.1.0/skmp-darwin-amd64"
      sha256 "719e1955cb6cea57711bc8c137a967a8564dc3f7c0d6e2ab2afc54eca3ed437b"

      define_method(:install) do
        bin.install "skmp-darwin-amd64" => "skmp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Nitesh000/skmp/releases/download/v0.1.0/skmp-darwin-arm64"
      sha256 "9837e3fb457a419375320069d3c5f2b80c7fa372da989b9550447157547de6d1"

      define_method(:install) do
        bin.install "skmp-darwin-arm64" => "skmp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Nitesh000/skmp/releases/download/v0.1.0/skmp-linux-amd64"
      sha256 "59c7771285fcb6c4c36c9666618bd2263d05fe79056b7f15894de4d9b4344fd9"
      define_method(:install) do
        bin.install "skmp-linux-amd64" => "skmp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Nitesh000/skmp/releases/download/v0.1.0/skmp-linux-arm64"
      sha256 "37ebbb1397bdb9515161f96a2a16ba463c00e4cf80b1dbcb02728f3d6b0c639e"
      define_method(:install) do
        bin.install "skmp-linux-arm64" => "skmp"
      end
    end
  end

  test do
    system "#{bin}/skmp version"
  end
end
