# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skmp < Formula
  desc "Skill marketplace for AI agent skills"
  homepage "https://github.com/Nitesh000/skmp"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Nitesh000/skmp/releases/download/v0.1.4/skmp-darwin-amd64"
      sha256 "ee3fbfd4d7135f0324424ab0a03ca2bc7525ea6928372663b3850b5ba4bf5b9a"

      define_method(:install) do
        bin.install "skmp-darwin-amd64" => "skmp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Nitesh000/skmp/releases/download/v0.1.4/skmp-darwin-arm64"
      sha256 "a5a1cfb4a9dd3ddec938d15969f99cc85431e317c890dde666c0b114687d21fe"

      define_method(:install) do
        bin.install "skmp-darwin-arm64" => "skmp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Nitesh000/skmp/releases/download/v0.1.4/skmp-linux-amd64"
      sha256 "650201f7203a3b38331cb418afb54df8972b16c70fbd57a154a564c2a3c85b84"
      define_method(:install) do
        bin.install "skmp-linux-amd64" => "skmp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Nitesh000/skmp/releases/download/v0.1.4/skmp-linux-arm64"
      sha256 "2db9266774b9071d20874cfaa3eb8443fd1d634800fa27717b246bf47efea94a"
      define_method(:install) do
        bin.install "skmp-linux-arm64" => "skmp"
      end
    end
  end

  test do
    system "#{bin}/skmp version"
  end
end
