# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skmp < Formula
  desc "Skill marketplace for AI agent skills"
  homepage "https://github.com/Nitesh000/skmp"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Nitesh000/skmp/releases/download/v0.2.0/skmp-darwin-amd64"
      sha256 "3e1c535cb4318bb6e818e52ecbe0408c3a63cc1018738c3990dd5ce9b548b29d"

      define_method(:install) do
        bin.install "skmp-darwin-amd64" => "skmp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Nitesh000/skmp/releases/download/v0.2.0/skmp-darwin-arm64"
      sha256 "a14d4f87d4298c6df14af9ac222bc25627a42b4e774483e4700e6907b33025b6"

      define_method(:install) do
        bin.install "skmp-darwin-arm64" => "skmp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Nitesh000/skmp/releases/download/v0.2.0/skmp-linux-amd64"
      sha256 "4514308d7df25c53f3a55f15ab8b02b6957efb21e4e42f993e346c9e8a0e1869"
      define_method(:install) do
        bin.install "skmp-linux-amd64" => "skmp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Nitesh000/skmp/releases/download/v0.2.0/skmp-linux-arm64"
      sha256 "e74c41fe5bbcd9bad7f2159eaff66726015cd53943c8a63979d2ad27a67887c6"
      define_method(:install) do
        bin.install "skmp-linux-arm64" => "skmp"
      end
    end
  end

  test do
    system "#{bin}/skmp version"
  end
end
